/* AUTOGENERATED SOURCE FILE */
#define main_default _hideaway_main_default
#define lcdInitConfig _hide_lcdInitConfig
#include "../../../firmware/applications/default.c"
#undef lcdInitConfig
#undef main_default

int lcdInitConfig() {
}

void main_default() {
}
