/* AUTOGENERATED SOURCE FILE */

#include <stdint.h>
#include <stdio.h>

void execute_file (const char * fname, uint8_t checksignature, uint8_t decode){
  fprintf(stderr,"execute_file: unimplemented\n");
}

void executeSelect(char *ext){
  fprintf(stderr,"executeSelect: unimplemented\n");
}
