/* AUTOGENERATED SOURCE FILE */

#define usbMSCWrite _hideaway_usbMSCWrite
#define usbMSCRead _hideaway_usbMSCRead
#define usbMSCInit _hideaway_usbMSCInit
#define usbMSCOff _hideaway_usbMSCOff
#include "../../../firmware/usb/usbmsc.c"
#undef usbMSCWrite
#undef usbMSCRead
#undef usbMSCInit
#undef usbMSCOff

#include <stdio.h>

void usbMSCWrite(uint32_t offset, uint8_t src[], uint32_t length) {
  fprintf(stderr,"unimplemented: usbMSCWrite(offset=%d, src, length=%d)\n",offset,length);
}
    
void usbMSCRead(uint32_t offset, uint8_t dst[], uint32_t length) {
  fprintf(stderr,"unimplemented: usbMSCRead(offset=%d, dst, length=%d)\n",offset,length);
}
    
void usbMSCInit(void) {
  fprintf(stderr,"unimplemented: usbMSCInit(void)\n");
}

void usbMSCOff(void) {
  fprintf(stderr,"unimplemented: usbMSCOff(void)\n");
}
